# 在线 web 目标识别
# 文件位置：$HOME/web_object_detection.yml

version: "3"
services:
  object_detection:
    image: tsanfer/web_object_detection
    container_name: object_detection
    ports:
      - 4000:4000 # Web 后端
      - 8000:8000 # Web 前端
    restart: unless-stopped
