# webdav 客户端
# 文件位置：$HOME/webdav-client.yml

version: "3"
services:
  webdav-client:
    container_name: webdav-client
    image: efrecon/webdav-client
    devices:
      - /dev/fuse
    cap_add: # 添加容器权限
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
    volumes:
      - /mnt/webdav:/mnt/webdrive:rshared # 挂载目录
    environment:
      - WEBDRIVE_URL # webdav 服务器地址
      - WEBDRIVE_USERNAME # webdav 用户名
      - WEBDRIVE_PASSWORD # webdav 密码
      - DAVFS2_IGNORE_DAV_HEADER=1 # 禁用 WebDAV 头检测的功能
    restart: unless-stopped
