version: "3.3"
services:
  zfile:
    container_name: zfile
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ~/zfile/db:/root/.zfile-v4/db
      - ~/zfile/logs:/root/.zfile-v4/logs
      - ~/zfile/file:/data/file
      - ~/application.properties:/root/application.properties
    image: zhaojun1998/zfile
